include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "bin/cache/**"
    - "lib/assets/**"
    - "**.gr.dart"
    - "ios/**"
    - "android/**"
    - "**.g.dart"
    - "**.freezed.**"
    - "**.config.**"
  plugins:
    - dart_code_linter
  #    - custom_lint
  strong-mode:
    implicit-casts: false
  errors:
    always_declare_return_types: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_empty_else: error
    avoid_field_initializers_in_const_classes: error
    avoid_final_parameters: error
    avoid_function_literals_in_foreach_calls: error
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null_for_void: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    cancel_subscriptions: error
    control_flow_in_finally: error
    directives_ordering: error
    empty_catches: error
    empty_constructor_bodies: error
    empty_statements: error
    hash_and_equals: error
    implementation_imports: error
    iterable_contains_unrelated_type: error
    library_names: error
    library_prefixes: error
    list_remove_unrelated_type: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    non_constant_identifier_names: error
    overridden_fields: error
    package_api_docs: error
    package_names: error
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_adjacent_string_concatenation: error
    prefer_asserts_in_initializer_lists: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    prefer_for_elements_to_map_fromIterable: error
    prefer_foreach: error
    prefer_generic_function_type_aliases: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_inlined_adds: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_is_not_operator: error
    prefer_iterable_whereType: error
    prefer_spread_collections: error
    prefer_typing_uninitialized_variables: error
    prefer_void_to_null: error
    recursive_getters: error
    slash_for_doc_comments: error
    invalid_annotation_target: ignore
    sort_pub_dependencies: error
    sort_unnamed_constructors_first: error
    test_types_in_equals: error
    throw_in_finally: error
    type_init_formals: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_getters_setters: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    unnecessary_statements: error
    unnecessary_this: error
    unused_import: error
    unused_catch_clause: error
    unrelated_type_equality_checks: error
    use_full_hex_values_for_flutter_colors: error
    use_rethrow_when_possible: error
    valid_regexps: error
    void_checks: error
    prefer_relative_imports: error
    require_trailing_commas: error
    avoid_multiple_declarations_per_line: error

custom_lint:
  rules:
    # Dart lints
    - always_put_doc_comments_before_annotations
    - always_specify_parameter_names
    - avoid_abbreviations_in_doc_comments
    - avoid_dynamic
    - avoid_empty_blocks
    - avoid_inverted_boolean_expressions
    - avoid_mutable_global_variables
    - avoid_nested_if
    - avoid_positional_fields_in_records
    - avoid_redundant_pattern_field_names
    - avoid_unused_parameters
    - boolean_prefixes
    - no_duplicate_imports
    - no_self_comparisons
    - prefer_async_await
    - prefer_const_constructor_declarations
    - prefer_immediate_return
    - prefer_iterable_any
    - prefer_iterable_every
    - prefer_iterable_first
    - prefer_iterable_last
    - prefer_library_prefixes
    - prefer_new_line_before_return
    - unnecessary_nullable_return_type
    # Flutter lints
    - avoid_public_members_in_states
    - avoid_returning_widgets
    - avoid_single_child_in_flex
    - dispose_controllers
    - prefer_async_callback
    - prefer_border_from_border_side
    - prefer_border_radius_all
    - prefer_dedicated_media_query_functions
    - prefer_text_rich
    - prefer_void_callback
    - proper_expanded_and_flexible
    - proper_from_environment
    - proper_super_dispose
    - proper_super_init_state
    - use_spacer

dart_code_linter:
  rules:
    - avoid-wrapping-in-padding
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-define-hero-tag
    - prefer-extracting-callbacks
    - use-setstate-synchronously
    - avoid-expanded-as-spacer
    - avoid-border-all
    - always-remove-listener
    - prefer-async-await
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - avoid-unnecessary-type-casts
    - binary-expression-operand-order
    - double-literal-format
    - avoid-unnecessary-conditionals
    - avoid-throw-in-catch-block
    - avoid-global-state
    - avoid-double-slash-imports
    - avoid-cascade-after-if-null
    - member-ordering:
        order:
          - static-fields
          - private-fields
          - public-fields
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - constructors
          - public-methods
          - private-methods
          - close-method
          - dispose-method
        widgets-order:
          - private-static-fields
          - private-const-fields
          - private-final-fields
          - private-late-fields
          - public-static-fields
          - public-const-fields
          - public-final-fields
          - public-late-fields
          - constructor
          - named-constructor
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - overridden-public-methods
          - build-method
          - dispose-method
          - private-methods
          - public-methods
    - prefer-static-class:
        ignore-private: true

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    #    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - collection_methods_unrelated_type
    - curly_braces_in_flow_control_structures
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_library_directive
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_named_constants
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks
    - avoid_multiple_declarations_per_line

