name: my_helper
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  alarm: ^3.1.3
  another_telephony: ^0.2.4
  auto_route: ^8.1.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  location: ^6.0.1
  overlay_support: ^2.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^9.0.0
  sound_mode: ^3.0.0
  vibration: ^1.8.4


dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  freezed: ^2.5.2
  hive_generator_plus: ^3.0.4
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  background_color: "#1F2C41"
  theme_color: "#1F2C41"
  adaptive_icon_background: "#1E1A1C"
  adaptive_icon_foreground: "assets/images/logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mp3/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900